### ISSUE TITLE
'Chunkenize' all! xD

### ISSUE THREAD

**Issue by CytraL** [CytraL/MineTee#11]
Currently the operations are working over all of the map... this affect to the server performance... try to do a system where only update the things that are really necessary...

**Comment by xushTW** [comment]
also nice for infinite random worlds :)

**Comment by CytraL** [comment]
Now refresh 2304 tiles (max.) per player and only check tiles which have not changed (when two or more players are close)... 

For dynamic generation best do a prefixed size, for example: small, medium, large, and generate the world... i prefer quality than quantity ;)
