### ISSUE TITLE
MineTee not compiling on windowns,mingw64

### ISSUE THREAD

**Issue by TSleepingCat** [CytraL/MineTee#29]
![Error](http://www.imghost.in/img/2016-08/06/x5mza7wj3031yj3mdiv0kp9up.png)

**Comment by CytraL** [comment]
Hi. For some reason bam are using lib32 instead lib64.
Try launching "bam -c", removing 'config.lua' file and try again...

**Comment by TSleepingCat** [comment]
and this error

**Comment by TSleepingCat** [comment]
wait

**Comment by TSleepingCat** [comment]
![Error](http://www.imghost.in/img/2016-08/07/npqx0o19o82hsqwksrjvdzgeb.png)

**Comment by TSleepingCat** [comment]
im think its problem of my compiler

**Comment by TSleepingCat** [comment]
but mingw not supports c++11

**Comment by CytraL** [comment]
Try with the 32 bits version :/

**Comment by TSleepingCat** [comment]
ye)

**Comment by CytraL** [comment]
Yeah it support c++11 i compile good with MinGW 32 bits :)

**Comment by TSleepingCat** [comment]
i'm found alien crypted message

**Comment by TSleepingCat** [comment]
![Error](http://www.imghost.in/img/2016-08/07/fdvsvxwha3i6n89thuo0nku54.png)

**Comment by TSleepingCat** [comment]
installed packages: Basic Setup > mingw32-base,mingw32-gcc-g++

**Comment by CytraL** [comment]
Wow xDD strange error :/
A few months ago that i not test compilation process under windows... i don't have windows now on my computer... but i remember that yes... are the correct packages.

Run 'bam -c'... check that 'config.lua' are good... i will try check this in one computer with windows.

**Comment by TSleepingCat** [comment]
AAAAAA MY OS IS STRANGE,NEED INSTALL LINUX

**Comment by CytraL** [comment]
Compile good in Windows 7 + MinGW32 + Python 2.7 + bam 0.5.0
