### ISSUE TITLE
Compilation in Visual Studio 2010 didn't work.

### ISSUE THREAD

**Issue by Stitch626** [CytraL/MineTee#31]
Ye, today i have a new issue for ur short list :)
It's impossible to compile MineTee with VS 2010. First i got an error in keystore.cpp telling me uint32_t isnt defined, can be fixed by including stdint.h .

Next fail i've got in noise.cpp, line 14. VS told me shuffle isn't an element of std. I found some informations in the Web, which says std::shuffle implemented in C++11, which vs 2010 and newer community/free editions didnt support. Best solution may be using random_shuffle instead of shuffle, but i'm not able to do it by myself. Reference:

http://en.cppreference.com/w/cpp/algorithm/random_shuffle

**Comment by CytraL** [comment]
Hi, thx for report...
For second issue... 'std::random_shuffle' is deprecated. Perhaps you need upgrade your visual c++ ide.

**Comment by Stitch626** [comment]
Visual Studio 2010 is already up to date. It's simply not possible to use std::shuffle because it came later in vs 2015/2013. It would be glad if u are able to backport the code fpr vs 2010 because vs isnt free (i have the pro edition of it)... I'm unable to do itself^^

**Comment by CytraL** [comment]
The problem with this fix is that you can't share seed's
