### ISSUE TITLE
Rename UNDEF & Spanish (?) Variables

### ISSUE THREAD

**Issue by xushTW** [CytraL/MineTee#6]
They should be all in english IMO.

(making a PR for this now...)

**Comment by xushTW** [comment]
Okay, sorry. Can't do it with my poor spanish skills.

**Comment by CytraL** [comment]
ok i go to do it... but my english is not the best xDD

**Comment by CytraL** [comment]
Issue affected by https://github.com/CytraL/MineTee/issues/3
